function plot_significant_anova_effects(mean_data, mean_labels, anova_outs, plot_subdir, varargin)

defaults = struct();
defaults.pcats = {'subject-type', 'task-id'};
defaults.addtl_pcats = {};
defaults.do_save = false;
defaults.config = hww5.config.load();
defaults.per_panel_labels = true;
defaults.points_are = { 'subject' };
params = shared_utils.general.parsestruct( defaults, varargin );

sig_subsets = hww5.generate_significant_anova_factor_subsets( ...
  mean_data, mean_labels', anova_outs.source_I, anova_outs.anova_tables );

for i = 1:numel(sig_subsets)
  sig_subset = sig_subsets{i};
  sig_plot_subdir = sprintf( '%s/sig/%s', plot_subdir, strjoin(sig_subset.factors, '__') );
  hww5.plot.ac_rt( sig_subset.data, sig_subset.labels ...
    , 'mean', false ...
    , 'norm', false ...
    , 'xcats', sig_subset.factors ...
    , 'pcats', [params.pcats, params.addtl_pcats] ...
    , 'points_are', params.points_are ...
    , 'do_save', params.do_save ...
    , 'config', params.config ...
    , 'per_panel_labels', params.per_panel_labels ...
    , 'plot_subdir', sig_plot_subdir ...
  );
end

end