function varargout = ba_lookdur(dur, labels, varargin)

[varargout{1:nargout}] = hww5.plot.ac_basic_bars( dur, labels ...
  , 'plot_subdir', 'basic_behavior/ba_lookdur' ...
  , 'y_label', 'lookdur (ms)' ...
  , varargin{:} ...
);

end