function varargout = gf_pcorr(pcorr, labels, varargin)

[varargout{1:nargout}] = hww5.plot.ac_basic_bars( pcorr, labels ...
  , 'plot_subdir', 'basic_behavior/gf_pcorr' ...
  , varargin{:} ...
);

end