%%  ja plots

is_drug = true;
subj_func = ternary( is_drug, @hww5.find_nhp, @hww5.find_nhp_saline_or_human );

find_task = @(l, id) @(m) find(l, id, m);

ja_mask_func = @(l, m) pipe(m ...
  , find_task(l, 'ja') ...
  , @(m) find(l, 'initiated-true', m) ...
  , @(m) subj_func(l, m) ...
);

ja_mask = ja_mask_func( outs.labels, rowmask(outs.labels) );
ja_labels = prune( outs.labels(ja_mask) );

[pcorr, pcorr_labels] = proportions_of( ja_labels, {'run-id'}, 'correct' );

norm_each = {'subject', 'correct'};
if ( norm_each_task_order )
  norm_each{end+1} = 'task-order';
end
norm_cats = {'drug'};
norm_labs = {'saline'};

if ( is_drug )
  gcats = {'drug'};
  pcats = {'correct', 'task-id', 'subject-type'};
else
  gcats = {'correct'};
  pcats = {'drug', 'task-id', 'subject-type'};
end

if ( is_drug )
  anova_factors = {'drug'};
else
  anova_factors = {'subject-type'};
end
if ( task_order_factor )
  anova_factors{end+1} = 'task-order';
end
anova_each = {};

do_save = true;
do_norm = true;
plot_subdir = 'basic_behavior/ja_pcorr';

[pcorr, pcorr_labels] = hww5.maybe_normalize_and_collapse( pcorr, pcorr_labels' ...
  , 'collapse', false ...
  , 'collapse_each', each ...
  , 'norm', do_norm ...
  , 'norm_each', norm_each ...
  , 'norm_cats', norm_cats ...
  , 'norm_labs', norm_labs ...
);

anova_outs = dsp3.anovan2( pcorr, pcorr_labels', anova_each, anova_factors );
if ( do_save )
  save_p = hww5.plot_directory( conf, fullfile(plot_subdir, 'stats') );
  dsp3.save_anova_outputs( anova_outs, save_p, [anova_factors, anova_each] );
end

hww5.plot_significant_anova_effects( pcorr, pcorr_labels', anova_outs, plot_subdir ...
  , 'do_save', do_save ...
  , 'addtl_pcats', anova_each ...
);

hww5.plot.ja_pcorr( pcorr, pcorr_labels ...
  , 'mask_func', @(l, m) m ...
  , 'mean', false ...
  , 'norm', false ...
  , 'xcats', {} ...
  , 'gcats', gcats ...
  , 'pcats', pcats ...
  , 'points_are', {'subject'} ...
  , 'y_label', '% correct' ...
  , 'do_save', do_save ...
  , 'plot_subdir', plot_subdir ...
  , 'per_panel_labels', true ...
);

%%  rt

sesh_I = findall( outs.labels, 'run-id' );
within_devs = hww5.logical_map_rows_each( ...
  outs.rt, sesh_I, @(data) hww5.within_deviations(data, 2) );

ja_rt_mask_func = @(l, m) pipe(m ...
  , find_task(l, 'ja') ...
  , @(m) find(l, 'initiated-true', m) ...
  , @(m) find(l, 'correct-true', m) ...
  , @(m) subj_func(l, m) ...
  , @(m) intersect(m, find(within_devs)) ...
);

% , @(m) hww5.find_nhp(l, m) ...

each = {'run-id', 'correct'};
norm_each = {'subject', 'correct'};
if ( norm_each_task_order )
  norm_each{end+1} = 'task-order';
end
norm_cats = {'drug'};
norm_labs = {'saline'};

gcats = {'correct', 'subject-type', 'drug'};
pcats = {'task-id'};

anova_each = {};
if ( is_drug )
  anova_factors = {'drug'};
else
  anova_factors = {'subject-type'};
end
if ( task_order_factor )
  anova_factors{end+1} = 'task-order';
end

plot_subdir = 'basic_behavior/ja_rt';

do_save = true;
do_norm = true;

[mean_rt, mean_labs] = hww5.maybe_normalize_and_collapse( outs.rt, outs.labels' ...
  , 'mask_func', ja_rt_mask_func ...
  , 'collapse', true ...
  , 'collapse_each', each ...
  , 'norm', do_norm ...
  , 'norm_each', norm_each ...
  , 'norm_cats', norm_cats ...
  , 'norm_labs', norm_labs ...
);

anova_outs = dsp3.anovan2( mean_rt, mean_labs', anova_each, anova_factors );
if ( do_save )
  save_p = hww5.plot_directory( conf, fullfile(plot_subdir, 'stats') );
  dsp3.save_anova_outputs( anova_outs, save_p, [anova_factors, anova_each] );
end

hww5.plot_significant_anova_effects( mean_rt, mean_labs', anova_outs, plot_subdir ...
  , 'do_save', do_save ...
  , 'addtl_pcats', anova_each ...
);

hww5.plot.ja_rt( mean_rt, mean_labs' ...
  , 'each', {} ...
  , 'mean', false ...
  , 'norm', false ...
  , 'xcats', {} ...
  , 'gcats', gcats ...
  , 'pcats', pcats ...
  , 'points_are', {'subject'} ...
  , 'do_save', do_save ...
  , 'plot_subdir', plot_subdir ...
);