conf = hww5.config.load();

filter_files_func = @identity;

outs = hww5_basic_behavior( ...
    'config', conf ...
  , 'is_parallel', true ...
  , 'task_ids', {'gf', 'ja'} ...
  , 'filter_files_func', filter_files_func ...
  , 'error_handler', 'error' ...
  , 'include_edf', false ...
);

require5_per_day = false;
hww5.labels.add_task_order( outs.labels, require5_per_day );
addcat( outs.labels, 'drug' );
add_subject_id( outs.labels );


%%

% task_ids = {'gf'};
task_ids = {'ja'};

mask_func = @(l, m) m;

hww5_basic_behavior_plots( outs ...
  , 'save', true ...
  , 'normalize', false ...
  , 'per_subject', false ...
  , 'task_ids', task_ids ...
  , 'norm_by_task_order', false ...
  , 'gf_per_delay', false ...
  , 'gf_consistent_minus_inconsistent_combs', false ...
  , 'gf_num_type', 'completed' ...
  , 'gf_per_trial_type', true ...
  , 'mask_func', mask_func ...
);

%%

function labels = add_subject_id(labels)

[run_I, run_C] = findall( labels, 'run-id' );
task_id_map = hww5_olga_task_id_to_subject_id();

for i = 1:numel(run_I)
  subj = task_id_map(run_C{i});
  setcat( labels, 'subject', subj, run_I{i} );
end

end