%%  ja plots

find_task = @(l, id) @(m) find(l, id, m);
find_saline = @(l) @(m) find(l, 'saline', m);

ja_mask_func = @(l, m) pipe(m ...
  , find_task(l, 'ja') ...
  , find_saline(l) ...
  , @(m) find(l, 'initiated-true', m) ...
);

ja_mask = ja_mask_func( outs.labels, rowmask(outs.labels) );
ja_labels = prune( outs.labels(ja_mask) );

[pcorr, pcorr_labels] = proportions_of( ja_labels, {'run-id'}, 'correct' );

hww5.plot.ja_pcorr( pcorr, pcorr_labels ...
  , 'mask_func', @(l, m) m ...
  , 'mean', false ...
  , 'xcats', {} ...
  , 'gcats', {'correct'} ...
  , 'pcats', {'drug', 'task-id'} ...
  , 'points_are', {'subject'} ...
  , 'y_label', '% correct' ...
  , 'do_save', true ...
);