%%  all task plots

is_drug = true;
subj_func = ternary( is_drug, @hww5.find_nhp, @hww5.find_nhp_saline_or_human );

pupil_mask_func = @(l, m) pipe(m ...
  , @(m) subj_func(l, m) ...
);

each = {'run-id', 'task-id'};
norm_each = {'subject', 'task-id'};
if ( norm_each_task_order )
  norm_each{end+1} = 'task-order';
end
norm_cats = {'drug'};
norm_labs = {'saline'};
anova_each = {};
anova_factors = { 'task-id' };
if ( is_drug )
  anova_factors{end+1} = 'drug';
end
if ( task_order_factor )
  anova_factors{end+1} = 'task-order';
end

do_norm = true;
do_save = true;

[pupil_dat, pupil_labs] = hww5.maybe_normalize_and_collapse( outs.pupil_size, outs.labels' ...
  , 'mask_func', pupil_mask_func ...
  , 'norm', do_norm ...
  , 'norm_each', norm_each ...
  , 'norm_cats', norm_cats ...
  , 'norm_labs', norm_labs ...
  , 'collapse_each', each ...
);

plot_subdir = 'basic_behavior/all_task_pupil';

anova_outs = dsp3.anovan2( pupil_dat, pupil_labs', anova_each, anova_factors );
if ( do_save )
  save_p = hww5.plot_directory( conf, fullfile(plot_subdir, 'stats') );
  dsp3.save_anova_outputs( anova_outs, save_p, [anova_factors, anova_each] );
end

xcats = {'task-id'};
gcats = {'drug'};
pcats = {};

hww5.plot.sm_pcorr( pupil_dat, pupil_labs ...
  , 'mean', false ...
  , 'norm', false ...
  , 'xcats', xcats ...
  , 'gcats', gcats ...
  , 'pcats', pcats ...
  , 'fcats', {} ...
  , 'points_are', {'subject'} ...
  , 'y_label', 'Pupil size' ...
  , 'y_lims', [] ...
  , 'do_save', do_save ...
  , 'config', conf ...
  , 'per_panel_labels', true ...
  , 'plot_subdir', plot_subdir ...
);

hww5.plot_significant_anova_effects( pupil_dat, pupil_labs', anova_outs, plot_subdir ...
  , 'do_save', do_save ...
  , 'addtl_pcats', anova_each ...
  , 'pcats', 'subject-type' ...
);