conf = hww5.config.load();

not_files = {'08-Jun-2021 15_07_55', '08-Jun-2021 15_08_06', '08-Jun-2021 15_07_49'};
filter_files_func = @(files) shared_utils.io.filter_files(files, {}, not_files);
% filter_files_func = @identity;

human_outs = hww5_basic_behavior( ...
    'config', conf ...
  , 'is_parallel', true ...
  , 'filter_files_func', filter_files_func ...
  , 'error_handler', 'error' ...
  , 'io_error_handler', 'warn' ...
  , 'include_edf', true ...
);

require5_per_day = false;
hww5.labels.add_task_order( human_outs.labels, require5_per_day );
addcat( human_outs.labels, 'drug' );
% add_subject_id( outs.labels );
addsetcat( human_outs.labels, 'subject-type', 'human' );

%%

% task_ids = {'gf'};
task_ids = {'ja'};

mask_func = @(l, m) m;

hww5_basic_behavior_plots( outs ...
  , 'save', true ...
  , 'normalize', false ...
  , 'per_subject', false ...
  , 'task_ids', task_ids ...
  , 'norm_by_task_order', false ...
  , 'gf_per_delay', false ...
  , 'gf_consistent_minus_inconsistent_combs', false ...
  , 'gf_num_type', 'completed' ...
  , 'gf_per_trial_type', true ...
  , 'mask_func', mask_func ...
);

%%

function labels = add_subject_id(labels)

[run_I, run_C] = findall( labels, 'run-id' );
task_id_map = hww5_olga_task_id_to_subject_id();

for i = 1:numel(run_I)
  subj = task_id_map(run_C{i});
  setcat( labels, 'subject', subj, run_I{i} );
end

end