%%  sm plots

find_task = @(l, id) @(m) find(l, id, m);
find_saline = @(l) @(m) find(l, 'saline', m);

collapse_delays = true;

sm_mask_func = @(l, m) pipe(m ...
  , find_task(l, 'sm') ...
  , find_saline(l) ...
  , @(m) find(l, 'initiated-true', m) ...
);

sm_mask = sm_mask_func( outs.labels, rowmask(outs.labels) );
sm_labels = prune( outs.labels(sm_mask) );

if ( collapse_delays )
  [to_rep, to_rep_with] = hww5.make_small_med_large_delay_labels( combs(sm_labels, 'delay') );
  for i = 1:numel(to_rep)
    replace( sm_labels, to_rep{i}, to_rep_with{i} );
  end
end

[pcorr, pcorr_labels] = proportions_of( ...
  sm_labels, {'run-id', 'delay', 'trial-type'}, 'correct' );

%%

hww5.plot.sm_pcorr( pcorr, pcorr_labels ...
  , 'mask_func', @(l, m) find(l, 'correct-true', m) ...
  , 'mean', false ...
  , 'xcats', {'delay'} ...
  , 'gcats', {'trial-type'} ...
  , 'pcats', {'drug', 'task-id', 'correct'} ...
  , 'fcats', {'subject'} ...
  , 'points_are', {'subject'} ...
  , 'y_label', '% correct' ...
  , 'y_lims', [0, 1] ...
  , 'do_save', true ...
  , 'config', conf ...
);